### ISSUE TITLE
This package is not installable

### ISSUE THREAD

**Issue by sobolevn** [Miserlou/JonesComplexity#18]
That's what happens when I try to install your package:

```
» pipenv install --dev jones-complexity
Installing jones-complexity…
Collecting jones-complexity
  Downloading jones-complexity-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/private/var/folders/qn/2gssw9hx48g81chw0398hlrr0000gn/T/pip-build-3599hfuv/jones-complexity/setup.py", line 14, in <module>
        from pypandoc import convert
    ModuleNotFoundError: No module named 'pypandoc'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qn/2gssw9hx48g81chw0398hlrr0000gn/T/pip-build-3599hfuv/jones-complexity/setup.py", line 17, in <module>
        README = open(os.path.join(os.path.dirname(__file__), 'README.md')).read()
    NameError: name 'os' is not defined
    
    ----------------------------------------

Error:  An error occurred while installing jones-complexity!
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/qn/2gssw9hx48g81chw0398hlrr0000gn/T/pip-build-3599hfuv/jones-complexity/
```

**Comment by iAnanich** [comment]
When will these changes became available from PyPI ?
If just want to install it:
```$ pip install jones-complexity
Collecting jones-complexity
  Downloading https://files.pythonhosted.org/packages/7c/94/e3fc33adcd42cfaf301575c42a9f816aa15b6ccaec8c97d8f6bb089afea7/jones-complexity-0.1.2.tar.gz
...
```
I end up with the same error.

**Comment by iAnanich** [comment]
It's strange, but cloning gives the same version:
```
$ pip install git+https://github.com/Miserlou/JonesComplexity.git@master
Collecting git+https://github.com/Miserlou/JonesComplexity.git@master
  Cloning https://github.com/Miserlou/JonesComplexity.git (to revision master) to /tmp/pip-req-build-m0bq6dn4
Installing collected packages: jones-complexity
  Running setup.py install for jones-complexity ... done
Successfully installed jones-complexity-0.1.2
```

**Comment by sobolevn** [comment]
Sorry, I am not able to finish this work right now. I will have some free time to work on this in a week, I guess.

You can help me with the docs, which are out of date right now. Without fixing them we can not release a new version. See #34
