### ISSUE TITLE
Missing setup.py

### ISSUE THREAD

**Issue by barbossa** [Miserlou/JonesComplexity#43]
@sobolevn hello,

Why did you remove `setup.py` in the https://github.com/Miserlou/JonesComplexity/commit/69b3104d00c41ef75384ff752b374405e5884caf commit? I can not install the package because of this error.

```
(venv) vladimir@vladimir:~/projects/test_project$ pip install git+https://github.com/Miserlou/JonesComplexity
Collecting git+https://github.com/Miserlou/JonesComplexity
  Cloning https://github.com/Miserlou/JonesComplexity to /tmp/pip-req-build-ss8dwfbc
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command /home/vladimir/projects/test_project/venv/bin/python3 /home/vladimir/projects/test_project/venv/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp0xd6m_lk:
  Traceback (most recent call last):
    File "/home/vladimir/projects/test_project/venv/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/vladimir/projects/test_project/venv/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/vladimir/projects/test_project/venv/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-wi775xxo/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 130, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-wi775xxo/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 112, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-wi775xxo/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 123, in run_setup
      f = getattr(tokenize, 'open', open)(__file__)
    File "/usr/lib/python3.5/tokenize.py", line 454, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: 'setup.py'
```

**Comment by sobolevn** [comment]
See https://github.com/Miserlou/JonesComplexity/issues/42

New version is still not released, I have reimplemented this tool in https://github.com/wemake-services/wemake-python-styleguide for my own needs.
