### ISSUE TITLE
Can not be installed with pip in python 3.6

### ISSUE THREAD

**Issue by fpuga** [Miserlou/JonesComplexity#44]
I'm getting this error message when installing in python 3.6 via pip

```
$ pip install jones-complexity
Collecting jones-complexity
  Using cached https://files.pythonhosted.org/packages/7c/94/e3fc33adcd42cfaf301575c42a9f816aa15b6ccaec8c97d8f6bb089afea7/jones-complexity-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-install-i39ubzor/jones-complexity/setup.py", line 14, in <module>
        from pypandoc import convert
    ModuleNotFoundError: No module named 'pypandoc'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-i39ubzor/jones-complexity/setup.py", line 17, in <module>
        README = open(os.path.join(os.path.dirname(__file__), 'README.md')).read()
    NameError: name 'os' is not defined
```

**Comment by sobolevn** [comment]
See https://github.com/Miserlou/JonesComplexity/issues/42

New version is still not released, I have reimplemented this tool in https://github.com/wemake-services/wemake-python-styleguide for my own needs.

**Comment by fpuga** [comment]
Thanks for reviewed i will take a look at your project. I also like strictest linters.

**Comment by AGeekInside** [comment]
Has there been any movement on this issue?

**Comment by sobolevn** [comment]
You can use https://github.com/wemake-services/wemake-python-styleguide

This project was completely ported there: https://github.com/wemake-services/wemake-python-styleguide/blob/c4043b5ba304a5781e8cfb81f4fb1272c00f2915/wemake_python_styleguide/visitors/ast/complexity/jones.py
